apiVersion: v1
kind: ConfigMap
metadata:
  name: book-review-config
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: configuration
    app.kubernetes.io/part-of: book-review-system
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "Configuration for Book Review Application"
data:
  # Spring Boot Configuration
  SPRING_PROFILES_ACTIVE: "production,docker"
  SERVER_PORT: "8080"
  
  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:h2:file:/app/data/bookreviews;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.H2Dialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  
  # H2 Console Configuration (disabled in production)
  SPRING_H2_CONSOLE_ENABLED: "false"
  
  # Actuator Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"
  MANAGEMENT_SERVER_PORT: "8080"
  
  # Security Configuration
  SPRING_SECURITY_REQUIRE_SSL: "false"
  SERVER_ERROR_INCLUDE_STACKTRACE: "never"
  SERVER_ERROR_INCLUDE_MESSAGE: "never"
  
  # Logging Configuration
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_BOOKREVIEW: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "WARN"
  LOGGING_LEVEL_ORG_HIBERNATE: "WARN"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  LOGGING_PATTERN_FILE: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # JVM Configuration
  JAVA_OPTS: "-Xms256m -Xmx512m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler"
  
  # Application Configuration
  APP_NAME: "Book Review Application"
  APP_VERSION: "1.0.0"
  APP_ENVIRONMENT: "production"
  
  # Performance Tuning
  SERVER_TOMCAT_MAX_THREADS: "200"
  SERVER_TOMCAT_MIN_SPARE_THREADS: "10"
  SERVER_TOMCAT_CONNECTION_TIMEOUT: "20000"
  
  # File Upload Configuration
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "5MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "10MB"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: book-review-app-properties
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/component: application-properties
data:
  application-production.properties: |
    # Production Configuration for Book Review Application
    
    # Server Configuration
    server.port=8080
    server.shutdown=graceful
    server.tomcat.connection-timeout=20000
    server.tomcat.max-threads=200
    server.tomcat.min-spare-threads=10
    
    # Database Configuration
    spring.datasource.url=jdbc:h2:file:/app/data/bookreviews;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    spring.datasource.driverClassName=org.h2.Driver
    spring.datasource.username=sa
    spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.format_sql=false
    
    # H2 Console (disabled in production)
    spring.h2.console.enabled=false
    
    # Actuator Configuration
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=when-authorized
    management.endpoints.web.base-path=/actuator
    management.server.port=8080
    
    # Security Configuration
    server.error.include-stacktrace=never
    server.error.include-message=never
    
    # Logging Configuration
    logging.level.root=INFO
    logging.level.com.bookreview=INFO
    logging.level.org.springframework.security=WARN
    logging.level.org.hibernate=WARN
    logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
    logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
    
    # File Upload Configuration
    spring.servlet.multipart.max-file-size=5MB
    spring.servlet.multipart.max-request-size=10MB
