apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review-app
  namespace: flask-app-namespace
  labels:
    app: book-review-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-review-app
  template:
    metadata:
      labels:
        app: book-review-app
    spec:
      containers:
      - name: book-review-app
        image: java-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: book-review-app-service
  namespace: flask-app-namespace
  labels:
    app: book-review-app
spec:
  selector:
    app: book-review-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
