apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review-app-simple
  namespace: flask-app-namespace
  labels:
    app: book-review-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-review-app
  template:
    metadata:
      labels:
        app: book-review-app
    spec:
      containers:
      - name: book-review-app
        image: openjdk:17-jdk-alpine
        command: ["sleep", "3600"]
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xmx512m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: book-review-app-service-simple
  namespace: flask-app-namespace
spec:
  selector:
    app: book-review-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
