apiVersion: v1
kind: Secret
metadata:
  name: book-review-secrets
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: secrets
    app.kubernetes.io/part-of: book-review-system
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "Secrets for Book Review Application"
type: Opaque
data:
  # Database password (base64 encoded)
  # Original value: "SecureP@ssw0rd123!"
  # To generate: echo -n "SecureP@ssw0rd123!" | base64
  db-password: U2VjdXJlUEBzc3cwcmQxMjMh
  
  # Application secret key for session management
  # Original value: "MySecretKeyForJWTTokenGeneration2024"
  # To generate: echo -n "MySecretKeyForJWTTokenGeneration2024" | base64
  app-secret-key: TXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24yMDI0
  
  # Encryption key for sensitive data
  # Original value: "EncryptionKey123456789"
  # To generate: echo -n "EncryptionKey123456789" | base64
  encryption-key: RW5jcnlwdGlvbktleTEyMzQ1Njc4OQ==
---
# Service Account for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-review-service-account
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: service-account
  annotations:
    description: "Service account for Book Review Application"
automountServiceAccountToken: false
secrets:
- name: book-review-secrets
