apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: book-review-app-pdb
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: pdb
  annotations:
    description: "Pod Disruption Budget for Book Review Application"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: book-review-app
      app.kubernetes.io/instance: production
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: book-review-app-hpa
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: hpa
  annotations:
    description: "Horizontal Pod Autoscaler for Book Review Application"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: book-review-app
  
  minReplicas: 3
  maxReplicas: 10
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
# Pod Security Policy (deprecated but included for compatibility)
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: book-review-app-psp
  namespace: book-rev-namespace
  labels:
    app.kubernetes.io/name: book-review-app
    app.kubernetes.io/component: security
  annotations:
    description: "Pod Security Policy for Book Review Application"
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  
  # Required to prevent escalations to root
  requiredDropCapabilities:
    - ALL
  
  # Allow specific capabilities needed by the application
  allowedCapabilities:
    - SETUID
    - SETGID
  
  # Allow core volume types
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  
  # Require containers to run as non-root user
  runAsUser:
    rule: 'MustRunAsNonRoot'
  
  # Require containers to run with specific group
  runAsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 1001
  
  # Require containers to run with specific supplemental groups
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 1001
  
  # Require containers to run with specific fs group
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 1001
  
  # Read-only root filesystem
  readOnlyRootFilesystem: true
  
  # Host network restrictions
  hostNetwork: false
  hostIPC: false
  hostPID: false
  
  # SELinux (if applicable)
  seLinux:
    rule: RunAsAny
